import type { Metadata } from "next";
import { Geist, Geist_Mono, Flavors, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const flavor = Flavors({
  variable: "--headerFlavor",
  subsets: ["latin"],
  weight: "400",
});

const robotoSlab = Roboto_Slab ({
  variable: "--font-roboto-slab",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${flavor.variable} ${robotoSlab.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
